version: '2'
services:
        ndncert1:
                restart: always
                image: cawka/ndncert-base:v1
                build:
                        context: .
                volumes:
                        - ./demo1:/cert-home
                        - /var/run:/var/run
                environment:
                        - HOME=/cert-home
                        - NDN_LOG=ndncert.*=ALL
                entrypoint:
                        - /usr/local/bin/ndncert-ca-server
                        - -f
                        - /cert-home/ca.conf
        ndncert2:
                extends: ndncert1
                volumes:
                        - ./demo2:/cert-home
        discovery1:
                restart: always
                image: cawka/ndncert-base:v1
                volumes:
                        - ./demo1:/cert-home
                        - /var/run:/var/run
                environment:
                        - HOME=/cert-home
                        - NDN_LOG=ndn.Face=ALL
                entrypoint:
                        - /usr/local/bin/icear-ca
        discovery2:
                extends: discovery1
                volumes:
                        - ./demo2:/cert-home

# To create a service, run
#     docker-compose up -d ndncert1 discovery1
# or
#     docker-compose up -d ndncert2 discovery2

